# Generated by Django 5.2.7 on 2025-11-30 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['emp_id'],
                'indexes': [models.Index(fields=['department'], name='hr_employee_departm_343e7e_idx'), models.Index(fields=['status'], name='hr_employee_status_75bd6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttritionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateField()),
                ('reason', models.CharField(choices=[('voluntary', 'Voluntary Resignation'), ('terminated', 'Termination'), ('retired', 'Retirement'), ('laid_off', 'Lay Off'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_record', to='hr.employee')),
            ],
            options={
                'ordering': ['-exit_date'],
                'indexes': [models.Index(fields=['exit_date'], name='hr_attritio_exit_da_ebbba3_idx'), models.Index(fields=['reason'], name='hr_attritio_reason_92f8bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half-day', 'Half-Day')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['emp', 'date'], name='hr_attendan_emp_id_a93372_idx'), models.Index(fields=['date'], name='hr_attendan_date_3a46d7_idx')],
                'unique_together': {('emp', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('annual', 'Annual Leave'), ('casual', 'Casual Leave'), ('unpaid', 'Unpaid Leave'), ('maternity', 'Maternity Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='hr.employee')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['emp', 'start_date'], name='hr_leaverec_emp_id_2a9a35_idx'), models.Index(fields=['leave_type'], name='hr_leaverec_leave_t_cbd7b8_idx')],
            },
        ),
    ]
